name: spinner_button
description: A simple button which can transform and show a progress indicator.  Forked from another project
version: 0.4.4-nullsafety.1
author:
  - Pascal Brosinski<pascal@brosinski.eu>
  - Eric Martineau<edspuzzle@gmail.com>
homepage: https://github.com/SunnyApp/progress_button

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dartxx: any
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
